DROP DATABASE IF EXISTS MovieApp;
CREATE DATABASE MovieApp;
USE MovieApp;

CREATE TABLE Country (
    CountryID INT AUTO_INCREMENT PRIMARY KEY,
    CountryName VARCHAR(100) NOT NULL,
	ISOCode CHAR(2) NOT NULL UNIQUE,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE File (
    FileID INT AUTO_INCREMENT PRIMARY KEY,
    FileName VARCHAR(100) NOT NULL,
    MIMEType VARCHAR(50) NOT NULL,
    `Key` VARCHAR(256) NOT NULL,
    URL VARCHAR(256) NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE User (
    UserID INT AUTO_INCREMENT PRIMARY KEY,
    Username VARCHAR(50) NOT NULL,
    FirstName VARCHAR(50) NOT NULL,
    LastName VARCHAR(50) NOT NULL,
    Email VARCHAR(255) NOT NULL UNIQUE,
    Password VARCHAR(256) NOT NULL,
    AvatarFileID INT,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (AvatarFileID) REFERENCES File(FileID) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE Person (
    PersonID INT AUTO_INCREMENT PRIMARY KEY,
    FirstName VARCHAR(50) NOT NULL,
    LastName VARCHAR(50) NOT NULL,
    Biography TEXT,
    DateOfBirth DATE,
    Gender ENUM('Male', 'Female', 'Other', 'Not specified'),
    CountryID INT,
    PrimaryPhotoFileID INT,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (CountryID) REFERENCES Country(CountryID) ON DELETE SET NULL ON UPDATE CASCADE,
    FOREIGN KEY (PrimaryPhotoFileID) REFERENCES File(FileID) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE Movie (
    MovieID INT AUTO_INCREMENT PRIMARY KEY,
    Title VARCHAR(100) NOT NULL,
    Description TEXT,
    Budget DECIMAL(12, 2),
    ReleaseDate DATE,
    Duration SMALLINT UNSIGNED,
    DirectorID INT,
    CountryID INT,
    PosterFileID INT,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (DirectorID) REFERENCES Person(PersonID) ON DELETE SET NULL ON UPDATE CASCADE,
    FOREIGN KEY (CountryID) REFERENCES Country(CountryID) ON DELETE SET NULL ON UPDATE CASCADE,
    FOREIGN KEY (PosterFileID) REFERENCES File(FileID) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE Genre (
    GenreID INT AUTO_INCREMENT PRIMARY KEY,
    GenreName VARCHAR(50) NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE MovieGenre (
    MovieID INT,
    GenreID INT,
    PRIMARY KEY (MovieID, GenreID),
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (MovieID) REFERENCES Movie(MovieID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (GenreID) REFERENCES Genre(GenreID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE `Character` (
    CharacterID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    Description TEXT,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE MovieCharacter (
    MovieCharacterID INT AUTO_INCREMENT PRIMARY KEY,
    MovieID INT,
    CharacterID INT,
    ActorID INT,
    Role ENUM('leading', 'supporting', 'background'),
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (MovieID) REFERENCES Movie(MovieID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (CharacterID) REFERENCES `Character`(CharacterID) ON DELETE SET NULL ON UPDATE CASCADE,
    FOREIGN KEY (ActorID) REFERENCES Person(PersonID) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE FavoriteMovies (
    UserID INT,
    MovieID INT,
    PRIMARY KEY (UserID, MovieID),
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (UserID) REFERENCES User(UserID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (MovieID) REFERENCES Movie(MovieID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE PersonPhotos (
    PersonID INT,
    FileID INT,
    PRIMARY KEY (PersonID, FileID),
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (PersonID) REFERENCES Person(PersonID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (FileID) REFERENCES File(FileID) ON DELETE CASCADE ON UPDATE CASCADE
);
